# Generated by Django 3.2.6 on 2023-03-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_auto_20230301_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
