# Generated by Django 3.2.6 on 2023-03-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_auto_20230301_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='coautor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_devolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='nome_emprestado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='tempo_duracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
