# Generated by Django 4.1.2 on 2023-03-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_alter_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='tempo_duracao',
        ),
    ]
